/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      // Enhanced mobile-first breakpoints aligned with Material-UI
      screens: {
        'xs': '0px',
        'sm': '600px',
        'md': '900px',
        'lg': '1200px',
        'xl': '1536px',
        'mobile-sm': '375px',
        'mobile-lg': '414px',
        'tablet-sm': '768px',
        'tablet-lg': '1024px',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
        'mobile-xs': '0.125rem',
        'mobile-sm': '0.375rem',
        'mobile-md': '0.75rem',
        'mobile-lg': '1.25rem',
        'touch-sm': '2.75rem',
        'touch-md': '3rem',
        'touch-lg': '3.5rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        'mobile-xs': ['0.6875rem', { lineHeight: '0.875rem' }],
        'mobile-sm': ['0.8125rem', { lineHeight: '1.125rem' }],
        'mobile-base': ['0.9375rem', { lineHeight: '1.375rem' }],
        'mobile-lg': ['1.0625rem', { lineHeight: '1.5rem' }],
      },
      minHeight: {
        'touch': '44px',
        'touch-comfortable': '48px',
        'touch-large': '56px',
        'mobile-header': '56px',
        'tablet-header': '64px',
        'mobile-nav': '60px',
      },
      minWidth: {
        'touch': '44px',
        'touch-comfortable': '48px',
        'touch-large': '56px',
        'mobile-button': '88px',
      },
      maxWidth: {
        'mobile': '100vw',
        'mobile-content': 'calc(100vw - 2rem)',
        'tablet': '768px',
        'desktop': '1200px',
        'wide': '1600px',
      },
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        secondary: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in-out',
        'fade-in-slow': 'fadeIn 0.4s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'slide-in-mobile': 'slideInMobile 0.25s ease-out',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
        'shake': 'shake 0.5s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideInMobile: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2px)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-2px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(2px)' },
        }
      },
      boxShadow: {
        'soft': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'medium': '0 4px 6px rgba(0, 0, 0, 0.07)',
        'strong': '0 10px 15px rgba(0, 0, 0, 0.1)',
        'mobile': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'mobile-strong': '0 4px 8px rgba(0, 0, 0, 0.15)',
        'focus': '0 0 0 3px rgba(59, 130, 246, 0.1)',
        'focus-strong': '0 0 0 3px rgba(59, 130, 246, 0.2)',
      },
      borderRadius: {
        'mobile': '6px',
        'mobile-lg': '8px',
        'mobile-xl': '12px',
        'touch': '8px',
      },
      zIndex: {
        'mobile-nav': '40',
        'mobile-drawer': '50',
        'mobile-modal': '60',
        'mobile-toast': '70',
        'mobile-tooltip': '80',
      },
    },
  },
  plugins: [],
}
