package hyperinit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const dockerComposeTemplate = `version: '3.8'

# Hyperion Local Development Stack
# Auto-generated by 'hyper init'
#
# Services:
#   - MongoDB: Primary database (port 27017)
#   - Qdrant: Vector database (ports 7333-7334)
#   - Ollama: GPU-accelerated embeddings (port 7335)
#
# Usage:
#   docker compose up -d              # Start all services
#   docker compose logs -f ollama     # Watch Ollama model download
#   docker compose down               # Stop all services
#   docker compose down -v            # Stop and remove data

services:
  # ==========================================
  # MongoDB - Primary Database
  # ==========================================
  mongodb:
    image: mongo:7.0
    container_name: hyper-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: hyper_db
    volumes:
      - hyper_mongodb_data:/data/db
      - hyper_mongodb_config:/data/configdb
    networks:
      - hyper-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ==========================================
  # Qdrant - Vector Database
  # ==========================================
  qdrant:
    image: qdrant/qdrant:latest
    container_name: hyper-qdrant
    ports:
      - "7333:6333"  # HTTP API (custom port to avoid collisions)
      - "7334:6334"  # gRPC API (custom port to avoid collisions)
    volumes:
      - hyper_qdrant_data:/qdrant/storage
    networks:
      - hyper-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "/dev/null", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ==========================================
  # Ollama - GPU-Accelerated Embeddings
  # ==========================================
  ollama:
    image: ollama/ollama:latest
    container_name: hyper-ollama
    ports:
      - "7335:11434"  # API (custom port to avoid collisions)
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
      OLLAMA_NUM_PARALLEL: 4
    volumes:
      - hyper_ollama_data:/root/.ollama
    networks:
      - hyper-network
    # Uncomment for NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ==========================================
  # Ollama Model Puller
  # Downloads nomic-embed-text model on first run
  # ==========================================
  ollama-pull:
    image: ollama/ollama:latest
    container_name: hyper-ollama-pull
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "
      echo '========================================';
      echo 'Downloading nomic-embed-text model...';
      echo 'This may take 2-5 minutes on first run';
      echo '========================================';
      ollama pull nomic-embed-text;
      echo '';
      echo '========================================';
      echo '✅ Model downloaded successfully!';
      echo 'Model: nomic-embed-text (768 dimensions)';
      echo 'Ollama URL: http://localhost:7335';
      echo '========================================';
      "
    environment:
      OLLAMA_HOST: ollama:11434
    networks:
      - hyper-network

# ==========================================
# Networks
# ==========================================
networks:
  hyper-network:
    driver: bridge
    name: hyper-network

# ==========================================
# Volumes (Persistent Storage)
# ==========================================
volumes:
  hyper_mongodb_data:
    driver: local
  hyper_mongodb_config:
    driver: local
  hyper_qdrant_data:
    driver: local
  hyper_ollama_data:
    driver: local
`

const envTemplate = `# Hyperion Configuration
# Auto-generated by 'hyper init'
#
# Edit this file to customize your Hyperion setup
# Documentation: https://github.com/your-repo/hyper

# ==========================================
# APPLICATION
# ==========================================
HTTP_PORT=7095
LOG_LEVEL=info

# ==========================================
# DATABASE (MongoDB)
# ==========================================
# Local Docker setup (default)
MONGODB_URI=mongodb://admin:admin123@localhost:27017/?authSource=admin
MONGODB_DATABASE=hyper_db

# For MongoDB Atlas (cloud), replace with your connection string:
# MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/?retryWrites=true&w=majority
# MONGODB_DATABASE=hyper_db

# ==========================================
# VECTOR DATABASE (Qdrant)
# ==========================================
# Local Docker setup (default) - using custom port 7333
QDRANT_URL=http://localhost:7333
QDRANT_API_KEY=

# For Qdrant Cloud, replace with your cluster URL:
# QDRANT_URL=https://your-cluster.qdrant.io:6333
# QDRANT_API_KEY=your-api-key

# Collection names
QDRANT_CODE_COLLECTION=hyper_code_index
QDRANT_KNOWLEDGE_COLLECTION=hyper_knowledge

# ==========================================
# EMBEDDINGS (Ollama - Local GPU)
# ==========================================
# Local Docker setup (default) - using custom port 7335
EMBEDDING=ollama
OLLAMA_URL=http://localhost:7335
OLLAMA_MODEL=nomic-embed-text

# Alternative: Voyage AI (Cloud - Production)
# EMBEDDING=voyage
# VOYAGE_API_KEY=pa-your-key-here
# VOYAGE_MODEL=voyage-3

# Alternative: OpenAI (Cloud)
# EMBEDDING=openai
# OPENAI_API_KEY=sk-your-key-here
# OPENAI_MODEL=text-embedding-3-small

# Alternative: TEI (CPU-based, slower)
# EMBEDDING=local
# TEI_URL=http://localhost:8080

# ==========================================
# CODE INDEXING (Optional)
# ==========================================
# Auto-scan folders on startup (comma-separated paths)
# INDEX_SOURCE_PATH=/path/to/your/code,/path/to/another/project
INDEX_SOURCE_PATH=

# Enable file watcher for automatic re-indexing
ENABLE_FILE_WATCHER=false

# Auto-recreate collection on dimension mismatch (when switching models)
CODE_INDEX_AUTO_RECREATE=false

# ==========================================
# AI CONFIGURATION (Optional - for Chat features)
# ==========================================
# AI_PROVIDER=anthropic
# ANTHROPIC_API_KEY=sk-ant-your-key-here
# AI_MODEL=claude-sonnet-4-20250514

# Generation settings
# MAX_ITERATIONS=1000
# MAX_TOOL_CALLS=500
# MAX_OUT_TOKENS=8000
# TEMPERATURE=0.3

# ==========================================
# SECURITY (Optional)
# ==========================================
# Restrict file operations to specific directories (comma-separated)
# ALLOWED_DIRS=/Users/you/projects,/Users/you/workspace
`

const readmeTemplate = `# Hyperion Local Setup

This directory was initialized with 'hyper init'.

## Quick Start

### 1. Start Services

    # Start MongoDB, Qdrant, and Ollama
    docker compose up -d

    # Watch Ollama model download (first time only, takes 2-5 minutes)
    docker compose logs -f ollama-pull

### 2. Run Hyper

    # Make sure you have the hyper binary
    # Build it if needed: cd /path/to/hyper && make native

    # Run hyper in HTTP mode
    ./hyper --mode=http

    # Or if hyper is in your PATH:
    hyper --mode=http

### 3. Access UI

Open your browser to: **http://localhost:7095**

## Services

| Service | URL | Port | Description |
|---------|-----|------|-------------|
| **Hyper UI** | http://localhost:7095 | 7095 | Web interface |
| **MongoDB** | mongodb://localhost:27017 | 27017 | Primary database |
| **Qdrant HTTP** | http://localhost:7333 | 7333 | Vector DB API |
| **Qdrant gRPC** | http://localhost:7334 | 7334 | Vector DB gRPC |
| **Ollama** | http://localhost:7335 | 7335 | Embeddings API |

## Configuration

Edit .env.hyper to customize your setup:
- Database connection strings
- Embedding provider (Ollama, Voyage AI, OpenAI)
- Code indexing paths
- AI provider settings

## Common Commands

    # View all service logs
    docker compose logs -f

    # View specific service logs
    docker compose logs -f ollama
    docker compose logs -f mongodb
    docker compose logs -f qdrant

    # Stop services
    docker compose down

    # Stop and remove all data
    docker compose down -v

    # Restart a specific service
    docker compose restart ollama

## Switching Embedding Providers

### Use Voyage AI (Cloud - Recommended for Production)

Edit .env.hyper:

    EMBEDDING=voyage
    VOYAGE_API_KEY=pa-your-key-here
    VOYAGE_MODEL=voyage-3

Then restart hyper.

### Use OpenAI (Cloud)

Edit .env.hyper:

    EMBEDDING=openai
    OPENAI_API_KEY=sk-your-key-here
    OPENAI_MODEL=text-embedding-3-small

Then restart hyper.

## Troubleshooting

### Check Service Health

    # MongoDB
    docker exec hyper-mongodb mongosh --eval "db.adminCommand('ping')"

    # Qdrant
    curl http://localhost:7333/health

    # Ollama
    curl http://localhost:7335/api/tags

### Ollama Model Issues

    # Re-download model
    docker exec hyper-ollama ollama pull nomic-embed-text

    # List downloaded models
    docker exec hyper-ollama ollama list

### Reset Everything

    # Stop and remove all data
    docker compose down -v

    # Restart
    docker compose up -d

## Port Conflicts

If you see port conflicts, this setup uses custom ports (7333-7335) to avoid common collisions.
You can change these in docker-compose.yml:

- Qdrant: 7333 (change both ports and .env.hyper)
- Ollama: 7335 (change both ports and .env.hyper)

## Next Steps

1. **Index your code:**
   - Edit .env.hyper and set INDEX_SOURCE_PATH
   - Restart hyper, it will auto-scan on startup

2. **Enable file watcher:**
   - Set ENABLE_FILE_WATCHER=true in .env.hyper
   - Hyper will auto-update index when files change

3. **Configure Claude Code integration:**
   - Run: make configure-native (from hyper repo)
   - Or manually add to Claude Code settings

## More Information

- **Full Documentation:** See MAKEFILE_AND_DOCKER_GUIDE.md in the hyper repo
- **Quick Reference:** See QUICK_REFERENCE.md in the hyper repo
- **GitHub:** https://github.com/your-repo/hyper
`

// ProviderConfig holds AI provider configuration
type ProviderConfig struct {
	Provider string
	Model    string
	Token    string
	APIURL   string
}

// validateOpenAI validates OpenAI API key
func validateOpenAI(apiKey string, model string, apiURL string) error {
	if apiURL == "" {
		apiURL = "https://api.openai.com/v1"
	}

	// Test with models endpoint (simple and fast)
	url := apiURL + "/models"
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to connect to OpenAI API: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 401 {
		return fmt.Errorf("invalid API key (HTTP 401)")
	}
	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API returned error (HTTP %d): %s", resp.StatusCode, string(body))
	}

	fmt.Println("✅ OpenAI API key validated successfully")
	return nil
}

// validateAnthropic validates Anthropic API key
func validateAnthropic(apiKey string, model string, apiURL string) error {
	if apiURL == "" {
		apiURL = "https://api.anthropic.com/v1"
	}

	// Test with messages endpoint (minimal request)
	url := apiURL + "/messages"
	payload := map[string]interface{}{
		"model":      model,
		"max_tokens": 1,
		"messages": []map[string]string{
			{"role": "user", "content": "test"},
		},
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to connect to Anthropic API: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 401 {
		return fmt.Errorf("invalid API key (HTTP 401)")
	}
	// 400 is ok - means API key works but request was invalid (expected for minimal test)
	if resp.StatusCode != 200 && resp.StatusCode != 400 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API returned error (HTTP %d): %s", resp.StatusCode, string(body))
	}

	fmt.Println("✅ Anthropic API key validated successfully")
	return nil
}

// validateVoyageAI validates Voyage AI API key
func validateVoyageAI(apiKey string, model string, apiURL string) error {
	if apiURL == "" {
		apiURL = "https://api.voyageai.com/v1"
	}

	// Test with embeddings endpoint
	url := apiURL + "/embeddings"
	payload := map[string]interface{}{
		"input": []string{"test"},
		"model": model,
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to connect to Voyage AI API: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 401 {
		return fmt.Errorf("invalid API key (HTTP 401)")
	}
	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API returned error (HTTP %d): %s", resp.StatusCode, string(body))
	}

	fmt.Println("✅ Voyage AI API key validated successfully")
	return nil
}

// validateProvider validates the provider configuration
func validateProvider(config *ProviderConfig) error {
	if config == nil || config.Provider == "" {
		// No provider specified, skip validation (will use Ollama default)
		return nil
	}

	fmt.Printf("\n🔐 Validating %s API credentials...\n", config.Provider)

	switch strings.ToLower(config.Provider) {
	case "openai":
		if config.Token == "" {
			return fmt.Errorf("OpenAI API token is required (use -token flag)")
		}
		if config.Model == "" {
			config.Model = "gpt-4" // Default model
		}
		return validateOpenAI(config.Token, config.Model, config.APIURL)

	case "anthropic", "claude":
		if config.Token == "" {
			return fmt.Errorf("Anthropic API token is required (use -token flag)")
		}
		if config.Model == "" {
			config.Model = "claude-sonnet-4-20250514" // Default model
		}
		return validateAnthropic(config.Token, config.Model, config.APIURL)

	case "voyage", "voyageai":
		if config.Token == "" {
			return fmt.Errorf("Voyage AI API token is required (use -token flag)")
		}
		if config.Model == "" {
			config.Model = "voyage-3" // Default model
		}
		return validateVoyageAI(config.Token, config.Model, config.APIURL)

	case "ollama":
		// Ollama doesn't require API key validation
		fmt.Println("ℹ️  Ollama selected - no API key validation needed")
		return nil

	default:
		return fmt.Errorf("unsupported provider: %s (supported: openai, anthropic, voyage, ollama)", config.Provider)
	}
}

// generateEnvWithProvider creates .env.hyper with provider configuration
func generateEnvWithProvider(config *ProviderConfig) string {
	env := envTemplate

	if config != nil && config.Provider != "" {
		provider := strings.ToLower(config.Provider)

		// Add AI provider configuration at the end
		aiConfig := "\n\n# ==========================================\n"
		aiConfig += "# AI PROVIDER CONFIGURATION\n"
		aiConfig += "# ==========================================\n"

		switch provider {
		case "openai":
			aiConfig += fmt.Sprintf("AI_PROVIDER=openai\n")
			aiConfig += fmt.Sprintf("OPENAI_API_KEY=%s\n", config.Token)
			aiConfig += fmt.Sprintf("AI_MODEL=%s\n", config.Model)
			if config.APIURL != "" {
				aiConfig += fmt.Sprintf("OPENAI_BASE_URL=%s\n", config.APIURL)
			}

			// Update embedding section
			env = strings.Replace(env, "EMBEDDING=ollama", "# EMBEDDING=ollama  # Using OpenAI for AI", 1)
			env = strings.Replace(env, "OLLAMA_URL=http://localhost:7335", "# OLLAMA_URL=http://localhost:7335", 1)
			env = strings.Replace(env, "OLLAMA_MODEL=nomic-embed-text", "# OLLAMA_MODEL=nomic-embed-text", 1)

		case "anthropic", "claude":
			aiConfig += fmt.Sprintf("AI_PROVIDER=anthropic\n")
			aiConfig += fmt.Sprintf("ANTHROPIC_API_KEY=%s\n", config.Token)
			aiConfig += fmt.Sprintf("AI_MODEL=%s\n", config.Model)
			if config.APIURL != "" {
				aiConfig += fmt.Sprintf("ANTHROPIC_BASE_URL=%s\n", config.APIURL)
			}

			// Keep Ollama for embeddings (Anthropic doesn't provide embeddings)
			aiConfig += "\n# Note: Still using Ollama for embeddings (Anthropic doesn't provide embeddings)\n"

		case "voyage", "voyageai":
			aiConfig += fmt.Sprintf("AI_PROVIDER=voyage\n")
			aiConfig += fmt.Sprintf("VOYAGE_API_KEY=%s\n", config.Token)

			// Update embedding section to use Voyage
			env = strings.Replace(env, "EMBEDDING=ollama", "EMBEDDING=voyage", 1)
			env = strings.Replace(env, "OLLAMA_URL=http://localhost:7335", "# OLLAMA_URL=http://localhost:7335", 1)
			env = strings.Replace(env, "OLLAMA_MODEL=nomic-embed-text", "# OLLAMA_MODEL=nomic-embed-text", 1)
			env = strings.Replace(env, "# EMBEDDING=voyage\n# VOYAGE_API_KEY=pa-your-key-here\n# VOYAGE_MODEL=voyage-3",
				fmt.Sprintf("# Voyage AI configured above\nVOYAGE_MODEL=%s", config.Model), 1)

			if config.APIURL != "" {
				aiConfig += fmt.Sprintf("VOYAGE_BASE_URL=%s\n", config.APIURL)
			}
		}

		env += aiConfig
	}

	return env
}

// Init creates a new Hyperion setup in the current directory
func Init(config *ProviderConfig) error {
	// Validate provider configuration if provided
	if err := validateProvider(config); err != nil {
		return fmt.Errorf("provider validation failed: %w", err)
	}
	// Check if files already exist
	files := []string{"docker-compose.yml", ".env.hyper"}
	var existingFiles []string

	for _, file := range files {
		if _, err := os.Stat(file); err == nil {
			existingFiles = append(existingFiles, file)
		}
	}

	if len(existingFiles) > 0 {
		fmt.Println("⚠️  The following files already exist:")
		for _, file := range existingFiles {
			fmt.Printf("   - %s\n", file)
		}
		fmt.Println()
		fmt.Print("Do you want to overwrite them? (yes/no): ")

		var response string
		fmt.Scanln(&response)

		if response != "yes" && response != "y" {
			return fmt.Errorf("initialization cancelled - files already exist")
		}
		fmt.Println()
	}

	// Create docker-compose.yml
	fmt.Println("📝 Creating docker-compose.yml...")
	if err := os.WriteFile("docker-compose.yml", []byte(dockerComposeTemplate), 0644); err != nil {
		return fmt.Errorf("failed to create docker-compose.yml: %w", err)
	}
	fmt.Println("✅ docker-compose.yml created")

	// Create .env.hyper with provider configuration
	fmt.Println("📝 Creating .env.hyper...")
	envContent := generateEnvWithProvider(config)
	if err := os.WriteFile(".env.hyper", []byte(envContent), 0644); err != nil {
		return fmt.Errorf("failed to create .env.hyper: %w", err)
	}
	fmt.Println("✅ .env.hyper created")

	// Create README.md
	fmt.Println("📝 Creating HYPER_README.md...")
	if err := os.WriteFile("HYPER_README.md", []byte(readmeTemplate), 0644); err != nil {
		return fmt.Errorf("failed to create HYPER_README.md: %w", err)
	}
	fmt.Println("✅ HYPER_README.md created")

	// Get current directory
	cwd, err := os.Getwd()
	if err != nil {
		cwd = "current directory"
	} else {
		cwd = filepath.Base(cwd)
	}

	// Print success message
	fmt.Println()
	fmt.Println("🎉 Hyperion initialized successfully!")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("📁 Location:", cwd)
	fmt.Println()
	fmt.Println("📝 Files created:")
	fmt.Println("   ✓ docker-compose.yml  - MongoDB + Qdrant + Ollama")
	fmt.Println("   ✓ .env.hyper          - Configuration file")
	fmt.Println("   ✓ HYPER_README.md     - Setup instructions")
	fmt.Println()
	fmt.Println("🚀 Next steps:")
	fmt.Println()
	fmt.Println("   1. Start services:")
	fmt.Println("      docker compose up -d")
	fmt.Println()
	fmt.Println("   2. Watch Ollama model download (first time, 2-5 min):")
	fmt.Println("      docker compose logs -f ollama-pull")
	fmt.Println()
	fmt.Println("   3. Run Hyper:")
	fmt.Println("      hyper --mode=http")
	fmt.Println()
	fmt.Println("   4. Open browser:")
	fmt.Println("      http://localhost:7095")
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	// Provider-specific tips
	if config != nil && config.Provider != "" {
		provider := strings.ToLower(config.Provider)
		fmt.Println("🔧 Provider Configuration:")
		fmt.Printf("   Provider: %s\n", provider)
		fmt.Printf("   Model: %s\n", config.Model)
		fmt.Printf("   Token: %s...%s\n", config.Token[:8], config.Token[len(config.Token)-4:])
		if config.APIURL != "" {
			fmt.Printf("   API URL: %s\n", config.APIURL)
		}
		fmt.Println()
	}

	fmt.Println("💡 Tip: Edit .env.hyper to customize your setup")
	fmt.Println("📖 See HYPER_README.md for detailed instructions")
	fmt.Println()

	return nil
}
